### ISSUE TITLE
Audit Trial

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#11]
Angaben machbar bzw. nachvollziehbar wer wann was wieso geändert hat

**Comment by christian-monch** [comment]
Die über das Web-Interface eingegebenen Daten werden auf dem Server einem Datalad Dataset hinzugefügt.

Das Datalad Dataset kann, durch berechtigte Personen geändert werden (mittels datalad-Kommandos). Datum, Autor und Art der Änderungen werden dabei im Datalad Dataset gespeichert.

Ein Web-Interface zur Modifikation bereitzustellen ist außerhalb des Projektumfangs (siehe auch issue #13) und würde mehrere Monate Zeit erfordern.
