### ISSUE TITLE
personalisierte Datenerfassung

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#12]
Name, Datum und Uhrzeit der Dateieingabe erfassen

**Comment by christian-monch** [comment]
Umsetzung durch folgende Aktivitäten:

- [x] Namens-Feld für Datenerfasser
- [x] Datum und Uhrzeit werden beim Speichern hinzugefügt
- [x] IP-Adresse des Klienten wird beim Speihern hinzugefügt

**Comment by christian-monch** [comment]
Umgesetzt in commit 4615089b278d5afc07418484d25019d470c99205

**Comment by VeronikaWu** [comment]
Super, vielen Dank
