### ISSUE TITLE
Signatur

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#13]
Berechtigte Personen können (von anderen Personen oder selbst) eingegebene Daten signieren und dadurch freigeben

**Comment by christian-monch** [comment]
Das Issue enthält zwei Use-Cases:

1. Eingegebene Daten signieren
2. Von Dritten eingegebene Daten abrufen, prüfen und signieren.

Der Use-Case 2 ist außerhalb des Scopes des Projekts, da er Eingabe und Prüfung/Signierung zeitlich entoppelt. Das würde ein Authentisierungssystem zur Abfrage der Daten erfordern, sowie eine Web-basierte Möglichkeit zur Dateneinsicht bzw. Datenänderung (im mindesten zum Signatur anfügen). 

> Bemerkung: statt einer Ausgabe von Daten über die Web-Schnittstelle wird der Datenexport zur Weiterverarbeitung prinzipiell entweder durch das Klonen des in Jülich gespeicherten Datalad-Datasets (welches die Rohdaten enthält) oder mittels eines Exports des Datasets in ein entsprechendes Format, z.B. csv-Tabelle, erfolgen.

Der Use-Case 1 kann von uns unterstützt werden. Wir können einen Hash-Wert generieren, der dem Inhalt der Daten auf der Eingabeseite eindeutig zugeordnet werden kann. Der Datenerfasser kann dann anhand dieser Zahlenfolge mit externen Tools eine Signatur erzeugen. Die Signatur bestätigt, dass der Datenerfasser die Daten so eingegeben hat, wie sie gespeichert werden. Diese Signatur können wir zusammen mit den Daten speichern. Beim Export können wir erneut einen Hash-Wert generieren und diesen und die Signatur mit exportieren. Mit Hilfe der externen Signierungstools läßt sich dann feststellen, ob der Datensatz unverändert ist und ob er vom genannten Datenerfasser eingegeben bzw. signiert wurde. Dazu sind folgende Schritte notwendig:

- [x] Separierung der Validierung und des Speicherns. Das ermöglicht die Nutzung des Hashwertes zur Signierung.
- [x] Erzeugung des Hashwertes
- [x] Hinzufügen eines Signatur-Feldes

**Comment by VeronikaWu** [comment]
Nur als Frage, ob das prinzipiell (rel. unkompliziert) möglich wäre: Könnte man sich die gerade eingegebenen Daten direkt ausdrucken lassen (beispielsweise als csv-Tabelle) ? Dann hätten wir über diesen Umweg vielleicht die Möglichkeit Use-Case 2 abzudecken.

**Comment by christian-monch** [comment]
> Nur als Frage, ob das prinzipiell (rel. unkompliziert) möglich wäre: Könnte man sich die gerade eingegebenen Daten direkt ausdrucken lassen (beispielsweise als csv-Tabelle) ? Dann hätten wir über diesen Umweg vielleicht die Möglichkeit Use-Case 2 abzudecken.

Wir können nach dem Speichern auf der Ergebnisseite alle gespeicherten Informationen (inklusive des Hash Values) noch einmal auflisten. Das könnte man dann ausdrucken (im Browser). 

(Das Ergebnis enthält neben dem Hash-Value auch einen eindeutigen Dateinamen. Durch Signieren eines der beiden Werte könnte ein Verantwortlicher die Daten abzeichnen. Manipulationen zwischen Empfang der Daten und dem Ausdruck könnte man durch Vergleich mit der Datenbank (oder durch eine Signierung der Daten durch den Server) entdecken. 

Der Aufwand beträgt hier ca. ein bis zwei Tage.

**Comment by VeronikaWu** [comment]
Vielen Dank für die Rückmeldung. Werde das so weitergeben und Bescheid sagen, sobald ich dazu mehr weiß.

**Comment by christian-monch** [comment]
Zunächst geschlossen, da alle Mechanismen für eine Uni-Klinik-seitige Signatur zur Verfügung stehen
