### ISSUE TITLE
RS mit Prof. Grefkes: Am wichtigsten wäre aber erstmal, dass man möglichst bald erste Daten eingeben und speichern kann 

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#14]
die anderen Änderungen (also auch Audit, Signatur und personalisierte Erfassung) können gerne im Verlauf erfolgen.

**Comment by christian-monch** [comment]
Zur Zeit ist eine Version verfügbar, in der Daten eingegeben werden können. Es sind nicht alle eIngabefeldübergreifenden Validierungen implementiert, die eingabefeldlokalen Validierungen sind komplett

Der Name des Erfassers kann angegeben werden,

Audit über Änderungen ist wie in #11 besprochen möglich.

 Nach der erfolgreichen Prüfung der Daten wird ein Hash-Value angezeigt (Teil der Implementierung von issue #13). Der Eefasser kann das hash-Value mit einem Tool seiner Wahl signieren und die Signatur im „Signatur-Daten“ Feld eingeben.

**Comment by christian-monch** [comment]
Die Ergebnisseite ist noch unübersichtlich, allerdings sollte klar erkennbar sein, ob ein Fehler vorliegt oder nicht.

Bei erfolgreicher Speicherung wird in etwa folgendes angezeigt

```
Referenz: 1624517500.7830925
SSL_TLS_SNI: sfb1451.inm7.de
GATEWAY_INTERFACE: CGI/1.1
SERVER_PROTOCOL: HTTP/1.1
REQUEST_METHOD: POST
QUERY_STRING: 
REQUEST_URI: /store-data
SCRIPT_NAME: /store-data

...
```

**Comment by christian-monch** [comment]
Erste Version inklusive Datenspeicherung ist fertig gestellt.

**Comment by christian-monch** [comment]
Daten werden vollständig gespeichert
