### ISSUE TITLE
RS Prof. Grefkes zu "Kästchen" 

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#15]
Prof. Grefkes fand den Vorschlag mit den anklickbaren Kästchen, genau wie heute Nachmittag besprochen, gut.
Sag sehr gerne Bescheid, falls ich dabei irgendwie helfen kann.

**Comment by christian-monch** [comment]
Ist mit commit 0e754e115b0b83a09adcaaa26af6113cbb3839cf 
eingeführt
