### ISSUE TITLE
KöpSS Dezimalzahlen

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#16]
Habe gerade nachgeschaut: Bei den Subtests "Sprache" und "Exekutive Leistungen" könnten auch Dezimalzahlen eingetragen werden. Habe es erst heute im Kleingedruckten bemerkt. Danke !

**Comment by christian-monch** [comment]
wurde geändert (commit 1910aff67cbf22cd369f71b4cdd2b1a7cb085289)
