### ISSUE TITLE
Kästchen sehen super aus, danke

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#17]
Auf den ersten Blick sieht das super aus und scheint auch unkompliziert anwendbar zu sein. Danke für die schnelle Umsetzung. 
Bei folgenden Tests würde ein Kästchen bei der Überschrift reichen:
ARAT, Purdue Pegboard Test, BDI, MADRS, mRS, EuroQol, Ausbildungsjahre. 
Falls das kompliziert ist, stört es aber auch nicht wirklich.

**Comment by christian-monch** [comment]
Ist in commit a7e78ef9a2fb1feeffc3fbe616170e2530117012
