### ISSUE TITLE
Go/Nogo-Task 1-6 Blöcke zur Auswahl 

### ISSUE THREAD

**Issue by VeronikaWu** [psychoinformatics-de/sfb1451_data_entry#9]
Wir wollen die Probanden jetzt doch gerne so viele Blöcke wie möglich durchführen lassen....also zwischen 1-6 Blöcken.
Könnte man also statt nur 2 oder 6 auch 1-6 auswählen lassen mit den entsprechenden Validierungen? Es sind jeweils maximal 60 "Punkte" pro Block (demnach bei 1 Block max 60, bei 2 Blöcken max 120 usw.)

**Comment by christian-monch** [comment]
Wird durch commit 703a9ed88d8097c139fc592043f835997252b81e realisiert.

Eingabfeldübergreifende Validierungen, werden getrennt behandelt (siehe issue #10)

@VeronikaWu: wenn keine weiteren Änderungen gewünscht sind, können wir dieses Issue schließen.

**Comment by VeronikaWu** [comment]
Hallo Christian,


oh das ist ja super, vielen Dank !


Liebe Grüße,

Veronika

________________________________
Von: Christian Mönch ***@***.***>
Gesendet: Montag, 14. Juni 2021 16:40:24
An: psychoinformatics-de/sfb1451_data_entry
Cc: Veronika Wunderle; Author
Betreff: Re: [psychoinformatics-de/sfb1451_data_entry] Go/Nogo-Task 1-6 Blöcke zur Auswahl (#9)


Wird durch commit 703a9ed<https://github.com/psychoinformatics-de/sfb1451_data_entry/commit/703a9ed88d8097c139fc592043f835997252b81e> realisiert.

Eingabfeldübergreifende Validierungen werden getrennt behandelt
